build_latest:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - rocker build --pull
    - docker tag $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master
  tags:
    - docker
    - rocker

build_develop:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - rocker build --pull
    - docker tag $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:develop"
    - docker push "$CI_REGISTRY_IMAGE:develop"
  only:
    - develop
  tags:
    - docker
    - rocker
